name: dev
variables:
  - name: BASE_URL
    value: http://localhost:3000/api/
  - secret: true
    name: USER_1
  - name: ROUND_ID
    value: 8fbbdc5d-4d44-4472-ab1e-af994b0b8164
  - secret: true
    name: USER_2
