name: dev
variables:
  - name: BASE_URL
    value: http://localhost:3000/api/
  - secret: true
    name: USER_1
  - name: ROUND_ID
    value: c4e5214c-3987-4a3b-9b3a-5d5dae4702fc
  - secret: true
    name: USER_2
